sonar.projectKey=factu
sonar.projectName=factu

sonar.sources=billing/src/main/java
sonar.tests=billing/src/test/java
sonar.java.binaries=billing/target/classes
sonar.java.test.binaries=billing/target/test-classes
sonar.junit.reportPaths=billing/target/surefire-reports

sonar.sourceEncoding=UTF-8
