server.port=8080
# Session store type.
spring.session.jdbc.initialize-schema=always
spring.session.timeout=900
#Dafult pgeabel values
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50


#*************************************************************************
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties) 
#*************************************************************************
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#*************************************************************************
# Disabling the /v3/api-docs endpoint
#*************************************************************************
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
# Disabling the swagger-ui
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}
# swagger-ui custom path
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-login-endpoint=true

springdoc.packagesToScan=com.paymentchain.billing.entities, com.paymentchain.billing.controller
springdoc.pathsToMatch=/v1, /billing/**

app.security.user.name=${APP_USER}
app.security.user.password=${APP_PASSWORD}
app.security.admin.name=${APP_ADMIN_USER}
app.security.admin.password=${APP_ADMIN_PASSWORD}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS}
